<script setup>
import maa from '@/assets/maa-gss.jpg'
</script>
<template>
    <AppHeader />
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-12 flex">
        <div class="w-1/4 p-3">
            <img :src="maa" class="w-full p-1 border-2 rounded-sm">
        </div>
        <div class="w-3/4 p-3">
            <h2 class="text-2xl font-bold border-b-2">Introduction</h2>
            <p class="text-base md:text-lg text-justify pb-1">GSS Girls' (P.G) College, an exclusive institution for girls, fulfils a long-standing need of Chirawa, a prominent town of Shekhawati region of Rajasthan. As late as the last quarter of the 20th century there was only one girls' school in the town run by Dalmia Education Trust. There was no college for girls. There was only one college in Chirawa, run by Somani Education Trust. Though people had started realizing the importance of women's education, they were still too conservative to permit their daughters to seek higher education in a co-educational college. The desire to educate their daughters in a congenial, tension free and protected environment led the leading citizens of Chirawa to request Shri Satyanarayanji Sekhsaria to start a college exclusively for girls. This request by the citizens of Chirawa under the leadership of Ex-M.L.A. late Shri Hazari lalji was readily accepted by Shri Satyanarayanji on the condition that Shri Hazarilalji Sharma would agree to become the Secretary of the Trust running the college. Shri Sharma agreed, and in no time it was decided to start the college. The Foundation stone of the college was laid on 19th November, 1986. 19th November happens to be the birth anniversary of Mrs. Indira Gandhi, the first woman Prime Minister of Independent India.</p>
            <p class="text-base md:text-lg text-justify pb-1"><strong>Ginnidevi Satyanarayan Sekhsaria Memorial Trust</strong> shares the ideals of Mrs. Gandhi, and firmly believes that the social, cultural and economic progress of any society is directly dependent on the education and enlightenment of its women folk. The college started functioning from July, 1987 in a well-furnished full-fledged, newly constructed building. The college got temporary affiliation to start teaching in all the three years of B.A. Pass Course. With a moderate strength of eighty students and teaching faculty in eight optional subjects the college started functioning in 1987. Shri Satyanarayanji barely lived to see his dream come true. Shri N.S. Sekhsaria, son of Shri Satyanarayanji is presently the Chairman of Ginnidevi Satyanarayan Sekhsaria Memorial Trust. His financial generosity is closely matched by his dream of seeing all the girls of Chirawa and nearby areas, transformed into confident, educated, self supporting young women who are responsible individuals fully prepared to successfully meet the challenges of life. Education is close to his heart, and he believes in the dictum "Educate a boy and an individual is educated, educate a girl and a family is educated".</p>
            <p class="text-base md:text-lg text-justify pb-1">In 1996, the college was taken on 90% grant in-aid by the Rajasthan Government. As the number of students in UG course increased, the need for starting PG teaching was felt. Thus in 1998 our college acquired the status of a PG college with the introduction of PG teaching in Hindi. At present, we run PG classes in Hindi, Political Science, Economics, Geography, History, English and Sanskrit.</p>
            <p class="text-base md:text-lg text-justify pb-1">The college boasts of a fine, compact, and aesthetically designed building and well laid lawns. Easy availability of fresh ground water helps in the maintenance of lush green lawns guarded by majestic Ashoka trees. Adjacent to the college campus we have the playground where students involve themselves in sports and games activities. There is a well furnished and well-equipped Computer Lab. We receive twenty four hour running drinking water. Three water coolers meet the need of the students' drinking water. To ensure clean drinking water, R.O. Plant (water purifier) has also been installed. There is Multipurpose Hall which is used by the students for their co-curricular and extra-curricular activities. Besides, the hall is also used for conducting talks, seminars and conferences.</p>
            <p class="text-base md:text-lg text-justify pb-1">The college also houses a Canteen which is run on co-operative basis. A multipurpose "stand" has also been constructed for parking the vehicles of the students and the staff. All basic amenities are provided to the students so that their stay in the college is a matter of pleasure for them. The college aims at providing the students a stress-free, relaxed, and eco-friendly environment.</p>
            
        </div>
    </div>
    <Footer />
</template>